import { readFileSync, readdirSync } from 'node:fs';
import assert from 'node:assert/strict';
const files=readdirSync('src').filter(f=>f.endsWith('.ts')).map(f=>'src/'+f);
const lines=path=>readFileSync(path,'utf8').split('\n').length-1;
const core=files.filter(f=>!['src/types.ts','src/laws.ts'].includes(f)).reduce((n,p)=>n+lines(p),0);
const total=files.concat('bin/check-kinds.mjs').reduce((n,p)=>n+lines(p),0);
assert(core<400,`Core runtime source exceeds 400 lines: ${core}`);
if(total>=400) assert(readFileSync('docs/guarantees.md','utf8').includes('Size exception:'),'Document the full source size exception');
assert(lines('README.md')<150,'README must remain under 150 lines');
console.log(`${core} core runtime lines; ${total} total with types, harness, and CLI; ${lines('README.md')} README lines.`);
